# application.yml
server:
  port: 9003

spring:
  application:
    name: emp-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 569811
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  oss:
    bucketName: java-ai-zck
    region: cn-beijing
    endpoint: https://oss-cn-beijing.aliyuncs.com